config/routes.rb
Malone::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :email_templates
  resources :sessions

  get  "/send_email/new/:id" => "send_email#prepare_to_send", :as =>:prepare_to_send
  post "/send_email" => "send_email#send_email", :as =>:send_emails

  root :to => 'email_templates#index'

end

app/models/email_template.rb
class EmailTemplate < ActiveRecord::Base
   attr_accessible :name, :subject, :body

   validates :name, :subject, :body, presence: true

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates :email, presence: true, uniqueness: true

  before_create { generate_token(:auth_token) }

  before_save do
    self.email = email.downcase
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Person.exists?(column => self[column])
  end

end

app/models/send_email.rb
require 'csv'

class SendEmail
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :filename, :email_template_id, :uploaded_file, :data, :content_type, :count

  validates_length_of :filename, :maximum => 500, :minimum => 1

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
    @count = 0
  end

  def persisted?
    false
  end

  def uploaded_file=(incoming_file)
    self.filename = incoming_file.original_filename
    self.content_type = incoming_file.content_type
    self.data = incoming_file.read
  end

  def send_all_emails()
    email_template = EmailTemplate.find(self.email_template_id)
    header = nil
    CSV.parse(data).each do |row|
      if (!header)
        header = row
      else
        data = Hash[header.zip row]
        send_one_email(email_template, data) unless row.empty?
      end
    end
    @count
  end

  def send_one_email(email_template, data)
    e_mail = {
        to: data['to'],
        subject: do_substitution(email_template.subject, data),
        body: do_substitution(email_template.body, data)
    }

    if (MaloneMailer.welcome_email(e_mail).deliver)
      @count = @count + 1
    end
  end

  def do_substitution(str, data_hash)
    puts "do_substitution ", str, data_hash
    str = str.clone
    data_hash.each do |k, v|
      str.gsub!('{{' + k.to_s + '}}', v)
    end
    str
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_person

  private

  helper_method :current_person

  def current_person
    @current_person ||= Person.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end

  def require_person
    unless current_person
      store_location
      flash[:info] = "You really need to sign in to get to that page."
      redirect_to new_session_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.url
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

end

app/controllers/email_templates_controller.rb
class EmailTemplatesController < ApplicationController

  # GET /email_templates
  # GET /email_templates.json
  def index
    @email_templates = EmailTemplate.all
    puts session
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @email_templates }
    end
  end

  # GET /email_templates/1
  # GET /email_templates/1.json
  def show
    @email_template = EmailTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @email_template }
    end
  end

  # GET /email_templates/new
  # GET /email_templates/new.json
  def new
    @email_template = EmailTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_template }
    end
  end

  # GET /email_templates/1/edit
  def edit
    @email_template = EmailTemplate.find(params[:id])
  end

  # POST /email_templates
  # POST /email_templates.json
  def create
    @email_template = EmailTemplate.new(params[:email_template])

    respond_to do |format|
      if @email_template.save
        format.html { redirect_to @email_template, notice: 'Email template was successfully created.' }
        format.json { render json: @email_template, status: :created, location: @email_template }
      else
        format.html { render action: "new" }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_templates/1
  # PUT /email_templates/1.json
  def update
    @email_template = EmailTemplate.find(params[:id])

    respond_to do |format|
      if @email_template.update_attributes(params[:email_template])
        format.html { redirect_to @email_template, notice: 'Email template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_templates/1
  # DELETE /email_templates/1.json
  def destroy
    @email_template = EmailTemplate.find(params[:id])
    @email_template.destroy

    respond_to do |format|
      format.html { redirect_to email_templates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/send_email_controller.rb
require "mail"

class SendEmailController < ApplicationController

  def prepare_to_send
    @email_template = EmailTemplate.find(params[:id])
    @send_email = SendEmail.new
    @send_email.email_template_id = @email_template.id
    respond_to do |format|
      format.html # prepare_to_send.html.erb
      format.json { render json: @email_template }
    end
  end

  def send_email
    puts '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&', params[:send_email], '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'
    send_email = SendEmail.new(params[:send_email])

    @email_template = EmailTemplate.find(send_email.email_template_id)

    @email_count = send_email.send_all_emails()

    respond_to do |format|
      format.html # prepare_to_send.html.erb
      format.json { render json: @email_template }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_person, :except => :destroy

  def new
  end

  def create
    host_name = Resolv.getname(request.ip)
    if (host_name.downcase.index("octanner.net") == nil) && (host_name.downcase.index("localhost") == nil)
      flash.now[:error] = "You can't get there from your machine - wrong network! (#{host_name})"
      render "new"
      return
    end


    person = Person.find_by_email(params[:session][:email])
    if person && person.authenticate(params[:session][:password])
      if params[:session][:remember_me] == "1"
        cookies.permanent[:auth_token] = { value: person.auth_token }
      else
        cookies[:auth_token] = { value: person.auth_token }
      end
      redirect_back_or_default root_path
    else
      flash.now[:error] = "Bummer! There was a problem with the email or password that you entered."
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    flash[:info] = "You logged out successfully!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_templates_helper.rb
module EmailTemplatesHelper
end

app/helpers/send_email_helper.rb
module SendEmailHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/email_templates/_form.html.erb
<%= form_for(@email_template) do |f| %>
  <% if @email_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_template.errors.count, "error") %> prohibited this email_template from being saved:</h2>

      <ul>
      <% @email_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :subject %>
      <%= f.text_field :subject %>
    </p>

    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_templates/edit.html.erb
<h1>Editing email_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_template %> |
<%= link_to 'Back', email_templates_path %>

app/views/email_templates/index.html.erb
<h1>Email Template Listing</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @email_templates.each do |email_template| %>
  <tr>
    <td><%= email_template.name%></td>
    <td><%= link_to 'Show', email_template %></td>
    <td><%= link_to 'Edit', edit_email_template_path(email_template) %></td>
    <td><%= link_to 'Destroy', email_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Send', prepare_to_send_path(email_template) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Email template', new_email_template_path %>

app/views/email_templates/new.html.erb
<h1>Create new e-Mail Template</h1>

<%= render 'form' %>

<%= link_to 'Back', email_templates_path %>

app/views/email_templates/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>


<p>
  Name
  </br>
  <%= @email_template.name %>
</p>

<p>
  Subject
  </br>
  <%= @email_template.subject %>
</p>

<p>
  Body
  </br>
  <%= @email_template.body %>
</p>

<%= link_to 'Edit', edit_email_template_path(@email_template) %> |
<%= link_to 'Back', email_templates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Malone - eMail Templating Service" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <script>
        var timer1;
    </script>
  </head>
  <body>
  <script>
      if (window['timer1'] != undefined){
          clearTimeout(timer1);
      }
  </script>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Malone - eMail Templating Service", root_path, class: "brand" %>
        <div class="container-fluid nav-collapse">
          <ul hidden class="nav">
            <ul hidden class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div><!--/row-->

    <footer>
      <p>&copy; O.C. Tanner 2013</p>
    </footer>

  </div> <!-- /container -->

  <!-- Javascripts
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/send_email/prepare_to_send.html.erb
<h1>Send Email</h1>

<%= form_for(@send_email, html: { multipart: true }) do |f| %>
    <% if @send_email.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@send_email.errors.count, "error") %> prohibited this send_email from being submitted:</h2>

          <ul>
            <% @send_email.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.hidden_field :email_template_id %>
    <p>
      <%= f.label :filename %>
      <%= f.text_field :filename %>
    </p>
    <p>
      <%= f.label :uploaded_file %>
      <%= f.file_field :uploaded_file  %>
    </p>

    <div class="actions">
      <%= f.submit("Send Emails") %>
    </div>
<% end %>

<%= link_to 'Edit', edit_email_template_path(@email_template) %> |
<%= link_to 'Back', email_templates_path %>

app/views/send_email/send_email.html.erb
<%= "#{@email_count} email(s) sent" %>

</br>
</br>

<%= link_to 'Back', email_templates_path %>